language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: dist
#   on:
#     branch: main

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "toy-littlefox-newsletter"
    